sudo: required

services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t zeozagart/multi-client ./client
  - docker build -t multi-nginx ./ngixn
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push -t zeozagart/multi-client
  - docker push -t zeozagart/multi-nginx
  - docker push -t zeozagart/multi-server
  - docker push -t zeozagart/multi-worker
